title: Jumaane Pond's Azure Cloud Misconfiguration Hunt
description: Cloud Security Posture Management (CSPM) Assessment & Remediation in Microsoft Azure
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight
